version: '3.4'

services:
  discodify:
    image: discodify
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3031:3031
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
