version: '3.4'

services:
  discodify:
    image: discodify
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3031:3031
